# this is the build file for project 
# it is autogenerated by the xmake build system.
# do not edit by hand.

ifneq ($(VERBOSE),1)
VV=@
endif

CXX=/usr/bin/gcc
MXX=/usr/bin/gcc
MM=/usr/bin/gcc
AS=/usr/bin/gcc
CU=/usr/bin/clang
GC=/usr/bin/go
CC=/usr/bin/gcc

SH=/usr/bin/g++
GCLD=/usr/bin/go
LD=/usr/bin/g++
GCAR=/usr/bin/go
AR=/usr/bin/ar

raylib-sandbox_LD=/usr/bin/g++
raylib-sandbox_CC=/usr/bin/gcc

raylib-sandbox_CCFLAGS=-m64 -g -Wall -Wextra -Wpedantic -O0 -std=c99 -isystem /home/yz/.xmake/packages/r/raylib/master/4e0143c97b65425b855ad5fd03038b6a/include
raylib-sandbox_LDFLAGS=-m64 -L/home/yz/.xmake/packages/r/raylib/master/4e0143c97b65425b855ad5fd03038b6a/lib -lraylib -lXrandr -lXinerama -lXcursor -lXrender -lX11 -lXi -lXfixes -lXext -lX11-xcb -lxcb -lxcb-composite -lxcb-damage -lxcb-dbe -lxcb-dpms -lxcb-dri2 -lxcb-dri3 -lxcb-glx -lxcb-present -lxcb-randr -lxcb-record -lxcb-render -lxcb-res -lxcb-screensaver -lxcb-shape -lxcb-shm -lxcb-sync -lxcb-xf86dri -lxcb-xfixes -lxcb-xinerama -lxcb-xinput -lxcb-xkb -lxcb-xtest -lxcb-xv -lxcb-xvmc -lXau -lXdmcp -lOpenGL -lpthread -ldl -lm

default:  raylib-sandbox

all:  raylib-sandbox

.PHONY: default all  raylib-sandbox

raylib-sandbox: build/linux/x86_64/debug/raylib-sandbox
build/linux/x86_64/debug/raylib-sandbox: build/.objs/raylib-sandbox/linux/x86_64/debug/src/main.c.o
	@echo linking.debug raylib-sandbox
	@mkdir -p build/linux/x86_64/debug
	$(VV)$(raylib-sandbox_LD) -o build/linux/x86_64/debug/raylib-sandbox build/.objs/raylib-sandbox/linux/x86_64/debug/src/main.c.o $(raylib-sandbox_LDFLAGS)

build/.objs/raylib-sandbox/linux/x86_64/debug/src/main.c.o: src/main.c
	@echo compiling.debug src/main.c
	@mkdir -p build/.objs/raylib-sandbox/linux/x86_64/debug/src
	$(VV)$(raylib-sandbox_CC) -c $(raylib-sandbox_CCFLAGS) -o build/.objs/raylib-sandbox/linux/x86_64/debug/src/main.c.o src/main.c

clean:  clean_raylib-sandbox

clean_raylib-sandbox: 
	@rm -rf build/linux/x86_64/debug/raylib-sandbox
	@rm -rf build/linux/x86_64/debug/raylib-sandbox.sym
	@rm -rf build/.objs/raylib-sandbox/linux/x86_64/debug/src/main.c.o

